//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion.Bici.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdReporte { get; set; }
        public Nullable<System.DateTime> FechaReporte { get; set; }
    }
}
