//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion.Bici.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoUsuario { get; set; }
        public Nullable<int> TelefonoUsuario { get; set; }
        public string DireccionUsuario { get; set; }
        public Nullable<int> RutUsuario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string CorreoUsuario { get; set; }
    }
}
